import { __sC, __sS } from "../sydneyDom_v3.js";

//abstract styles
__sS([
    {
        nameTag:"outline",
        style:{outline:"2px dashed #fff"}
    },
    {
        nameTag:"no-txt",
        style:{
            pointerEvents:"none"
        }
    },
    {
        nameTag:"bx-shadow",
        style:{
            boxShadow:"0px 0px 3px #000"
        }
    },
    {
        nameTag:"box",
        style:{
            height:"fit-content",
            width:"fit-content",
            padding:"10px"
        }
    },
    {
        nameTag:"thinBorder",
        style:{
            border:"1px solid rgba(0,0,0,.3)"
        }
    },
    {
        nameTag:"br-1",
        style:{
            borderRadius:"1rem"
        }
    },
    {
        nameTag:"br-.5",
        style:{
            borderRadius:".5rem"
        }
    },
    {
        nameTag:"row-start",
        style:{
            display:"flex",
            flexDirection:"row",
            alignItems:"center"
        }
    },
        {
        nameTag:"row-space",
        style:{
            display:"flex",
            flexDirection:"row",
            justifyContent:"space-around"
        }
    },
    {
        nameTag:"row-center",
        style:{
            display:"flex",
            flexDirection:"row",
            alignItems:"center",
            justifyContent:"center"
        }
    },
        {
        nameTag:"col-start",
        style:{
            display:"flex",
            flexDirection:"column",
            alignItems:"flex-start"
        }
    },
    {
        nameTag:"col-center",
        style:{
            display:"flex",
            flexDirection:"column",
            alignItems:"center",
        }
    },
    {
        nameTag:"h-txt",
        style:{
            textTransform:"capitalize",
            fontFamily:"header",
            fontWeight:"700"
        }
    },
    {
        nameTag:"n-txt",
        style:{
            textTransform:"capitalize",
            fontFamily:"font1",
            fontWeight:"500",
            minWidth:"max-content"
        }
    },
    {
        nameTag:"n-icon",
        style:{
            height:"18px",
            width:"18px",
            minHeight:"18px",
            minWidth:"18px",
            cursor:"pointer"
        }
    },
    {
        nameTag:"n2-icon",
        style:{
            height:"25px",
            width:"25px",
            cursor:"pointer"
        }
    },
    {
        nameTag:"copy-txt",
        style:{
            cursor:"pointer"
        }
    }
])
//abstract styles

__sS([
    {
        nameTag:"container",
        style:{
            height:"100vh",
            width:"100vw",
            poition:"relative",
            display:"flex",
            justifyContent:"center",
            alignItems:"center",
            transition:"none"
        }
    },
    {
        nameTag:"topNav",
        style:{
            height:"80px",
            width:"100%",
            background:"#ffffff",
            backgroundRepeat:"no-repeat",
            position:"absolute",
            top:"0px",
            left:"0px",
            zIndex:"999",
            overflow:"hidden"
        }
    },
    {
        nameTag:"sideNav",
        style:{
            height:"calc(100% - 70px)",
            background:"#ffffff",
            backgroundRepeat:"no-repeat",
            position:"relative",
            marginTop:"80px",
            top:"70px",
            left:"0px",
            zIndex:"10",
            // overflow:"hidden",
            padding:"10px",
            paddingTop:"10px"
        }
    },
    {
        nameTag:"highlight",
        style:{
            position:"absolute",
            bottom:"0px",
            height:"2px",
            minWidth:"50px"
        }
    },
    {
        nameTag:"highlight-side",
        style:{
            position:"absolute",
            left:"0px",
            width:"2px",
            minHeight:"10px"
        }
    },
    {
        nameTag:"mobileMenu",
        style:{
            height:"30px",
            width:"30px",
            position:"absolute",
            top:"50%",
            transform:"translateY(-50%)",
            right:"20px",
            cursor:"pointer",
            transition:".2s ease"
        }
    },
    {
        nameTag:"getPro",
        style:{
            height:"180px",
            width:"180px",
            position:"absolute",
            bottom:"40px",
            left:"50%",
            transform:"translateX(-50%)",
            padding:"7px",
            paddingBottom:"40px"
        }
    },
    {
        nameTag:"cr-40",
        style:{
            cursor:"pointer",
            height:"50px",
            width:"50px",
            padding:"unset"
        }
    },
    {
        nameTag:"notification",
        style:{
            height:"fit-content",
            width:"calc(100% - 20px)",
            padding:"20px",
            display:"flex",
            flexDirection:"column",
            gap:"5px",
            border:"1px solid rgba(255 , 255 , 255 , .1)",
            zIndex:"10000",
            position:"absolute",
            bottom:"20px",
            right:"10px",
            borderRadius:"10px",
            maxWidth:"400px"
        }
    }
])